# Truthy (Verdaderos)
print(bool(True))
print(bool(1))
print(bool(123))
print(bool(1.1))
print(bool(-1))
print(bool(1j))
print(bool('Hola'))
print(bool([1, 2, 3]))
print(bool((1, 2, 3)))
print(bool({1, 2, 3}))

# Falsy (Falsos)
print(bool(False))
print(bool(0))
print(bool(0.0))
print(bool(0j))
print(bool(''))
print(bool([]))
print(bool(()))
print(bool({}))
print(bool(None))
