[project]
name = "example"
version = "0.1.0"
description = "Mi ejemplo"
authors = [
    {name = "JesusPereira-ctrl",email = "jesuspereirap100@gmail.com"}
]
requires-python = ">=3.14"
dependencies = [
    "requests (>=2.34.2,<3.0.0)",
    "flask (>=3.1.3,<4.0.0)",
    "rich (>=15.0.0,<16.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
